'use strict';

/**
 * @ngdoc function
 * @name tonygApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the tonygApp
 */
angular.module('tonygApp')
  .controller('MainCtrl', function ($scope, $animate, Lightbox) {

    $('#carousel-portfolio').carousel();

    $scope.images = [
                      "images/portfolio/2_bcc_logo.png", 
                      "images/portfolio/3_bcc_donate.png", 
                      "images/portfolio/4a_cw_idtheft_1.png",
                      "images/portfolio/4b_cw_idtheft_2.png",
                      "images/portfolio/4c_cw_idtheft_3.png",
                      "images/portfolio/4d_cw_idtheft_4.png",
                      "images/portfolio/5_et_tablecard_1.png", 
                      "images/portfolio/6_et_sunset_ad.png", 
                      "images/portfolio/7_et_menu-full.png", 
                      "images/portfolio/8_tf_kiss_banner.png", 
                      "images/portfolio/9_tf_love_banner.png",
                      "images/portfolio/10_tf_degreesoflove.png",
                      "images/portfolio/11_tf_texasflorist-ad.png",
                      "images/portfolio/12_coh_centenial_book.png",
                      "images/portfolio/13_coh_kwak-postcard.png",
                      "images/portfolio/14_coh_hem_brochure.png",
                      "images/portfolio/15_coh_hemmal_brochure-cover.png",
                      "images/portfolio/16_red_rocket_ad_2.png",
                      "images/portfolio/17_hamms_bank_ad.png",
                      "images/portfolio/18_suzuki_outdoor.png",
                      "images/portfolio/21_tf_xmas-poster.png",
                      "images/portfolio/22_tf_MDay16-Banner-alt.png",
                      "images/portfolio/23_tahiti_ad.png",
                      "images/portfolio/24_et_angels_ad_1.png",
                      "images/portfolio/25_et_angels_ad_2.png",
                      "images/portfolio/26_et_angels_ad_3.png",
                      "images/portfolio/27_et_angels_insert_2.png",
                      "images/portfolio/28_wf_ad_1.png",
                      "images/portfolio/29_wf_ad_2.png",
                      "images/portfolio/30_wf_poster_1.png",
                      "images/portfolio/31_wf_poster_3.png",
                      "images/portfolio/32_et_tablecard_3.png",
                      "images/portfolio/33_cw_trade_ad_1.png",
                      "images/portfolio/34_cw_trade_ad_2.png",
                      "images/portfolio/35_cw_trade_ad_3.png",
                      "images/portfolio/1_tf_cubes_TG-version.png",
                      ]

                      $scope.imagesLightbox = [
                        {url:"images/portfolio-lb/2_bcc_logo.png",
                         caption:"Corporate Re-brand - New Logo"}, 
                        {url:"images/portfolio-lb/3_bcc_donate.png",
                         caption:"Online Ad"}, 
                        {url:"images/portfolio-lb/4a_cw_idtheft.png",
                         caption:"Consumer Brochure Cover"}, 
                        {url:"images/portfolio-lb/4b_cw_idtheft_2.png",
                         caption:"Consumer Brochure Inside"}, 
                        {url:"images/portfolio-lb/4c_cw_idtheft_3.png",
                         caption:"Consumer Brochure Inside"}, 
                        {url:"images/portfolio-lb/4d_cw_idtheft_4.png",
                         caption:"Consumer Brochure Inside"}, 
                        {url:"images/portfolio-lb/5_et_tablecard_1.png",
                         caption:"Table Card"},
                        {url:"images/portfolio-lb/6_et_sunset_ad.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/7_et_menu-full.png",
                         caption:"Collateral"},
                        {url:"images/portfolio-lb/8_tf_kiss_banner.png",
                         caption:"Online Ad"},
                        {url:"images/portfolio-lb/9_tf_love_banner.png",
                         caption:"Online Ad"},
                        {url:"images/portfolio-lb/10_tf_degreesoflove.png",
                         caption:"Florist Shop Poster"},
                        {url:"images/portfolio-lb/11_tf_texasflorist-ad.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/12_coh_centenial_book.png",
                         caption:"Collateral"},
                        {url:"images/portfolio-lb/13_coh_kwak-postcard.png",
                         caption:"Direct Mail Postcard (B-2-B)"},
                        {url:"images/portfolio-lb/14_coh_hem_brochure.png",
                         caption:"Brochure/Self-mailer (B-2-B)"},
                        {url:"images/portfolio-lb/15_coh_hemmal_brochure-cover.png",
                         caption:"Brochure/Self-mailer (B-2-B)"},
                        {url:"images/portfolio-lb/16_red_rocket_ad_2.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/17_hamms_bank_ad.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/18_suzuki_outdoor.png",
                         caption:"Outdoor Board"},
                        {url:"images/portfolio-lb/21_tf_xmas-poster.png",
                         caption:"Online Ad"},
                        {url:"images/portfolio-lb/22_tf_MDay16-Banner-alt.png",
                         caption:"Online Ad"},
                        {url:"images/portfolio-lb/23_tahiti_ad.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/24_et_angels_ad_1.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/25_et_angels_ad_2.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/26_et_angels_ad_3.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/27_et_angels_insert_2.png",
                         caption:"Direct Mail Insert"},
                        {url:"images/portfolio-lb/28_wf_ad_1.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/29_wf_ad_2.png",
                         caption:"Print Ad"},
                        {url:"images/portfolio-lb/30_wf_poster_1.png",
                         caption:"In-store Poster"},
                        {url:"images/portfolio-lb/31_wf_poster_3.png",
                         caption:"In-store Poster"},
                        {url:"images/portfolio-lb/32_et_tablecard_3.png",
                         caption:"Table Card"},
                        {url:"images/portfolio-lb/33_cw_trade_ad_1.png",
                         caption:"Trade Ad"},
                        {url:"images/portfolio-lb/34_cw_trade_ad_2.png",
                         caption:"Trade Ad"},
                        {url:"images/portfolio-lb/35_cw_trade_ad_3.png",
                         caption:"Trade Ad"},
                         {url:"images/portfolio-lb/1_tf_cubes_TG-version.png",
                          caption:"Online Ad"}
                      ]

                      $scope.imagesLightboxFirstIncluded = [ 
                          {url:"images/portfolio-lb/1_tf_cubes_TG-version.png",
                           caption:"Online Ad"},
                          {url:"images/portfolio-lb/2_bcc_logo.png",
                           caption:"Corporate Re-brand - New Logo"}, 
                          {url:"images/portfolio-lb/3_bcc_donate.png",
                           caption:"Online Ad"}, 
                          {url:"images/portfolio-lb/4a_cw_idtheft.png",
                           caption:"Consumer Brochure Cover"}, 
                          {url:"images/portfolio-lb/4b_cw_idtheft_2.png",
                           caption:"Consumer Brochure Inside"}, 
                          {url:"images/portfolio-lb/4c_cw_idtheft_3.png",
                           caption:"Consumer Brochure Inside"}, 
                          {url:"images/portfolio-lb/4d_cw_idtheft_4.png",
                           caption:"Consumer Brochure Inside"}, 
                          {url:"images/portfolio-lb/5_et_tablecard_1.png",
                           caption:"Table Card"},
                          {url:"images/portfolio-lb/6_et_sunset_ad.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/7_et_menu-full.png",
                           caption:"Collateral"},
                          {url:"images/portfolio-lb/8_tf_kiss_banner.png",
                           caption:"Online Ad"},
                          {url:"images/portfolio-lb/9_tf_love_banner.png",
                           caption:"Online Ad"},
                          {url:"images/portfolio-lb/10_tf_degreesoflove.png",
                           caption:"Florist Shop Poster"},
                          {url:"images/portfolio-lb/11_tf_texasflorist-ad.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/12_coh_centenial_book.png",
                           caption:"Collateral"},
                          {url:"images/portfolio-lb/13_coh_kwak-postcard.png",
                           caption:"Direct Mail Postcard (B-2-B)"},
                          {url:"images/portfolio-lb/14_coh_hem_brochure.png",
                           caption:"Brochure/Self-mailer (B-2-B)"},
                          {url:"images/portfolio-lb/15_coh_hemmal_brochure-cover.png",
                           caption:"Brochure/Self-mailer (B-2-B)"},
                          {url:"images/portfolio-lb/16_red_rocket_ad_2.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/17_hamms_bank_ad.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/18_suzuki_outdoor.png",
                           caption:"Outdoor Board"},
                          {url:"images/portfolio-lb/21_tf_xmas-poster.png",
                           caption:"Online Ad"},
                          {url:"images/portfolio-lb/22_tf_MDay16-Banner-alt.png",
                           caption:"Online Ad"},
                          {url:"images/portfolio-lb/23_tahiti_ad.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/24_et_angels_ad_1.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/25_et_angels_ad_2.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/26_et_angels_ad_3.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/27_et_angels_insert_2.png",
                           caption:"Direct Mail Insert"},
                          {url:"images/portfolio-lb/28_wf_ad_1.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/29_wf_ad_2.png",
                           caption:"Print Ad"},
                          {url:"images/portfolio-lb/30_wf_poster_1.png",
                           caption:"In-store Poster"},
                          {url:"images/portfolio-lb/31_wf_poster_3.png",
                           caption:"In-store Poster"},
                          {url:"images/portfolio-lb/32_et_tablecard_3.png",
                           caption:"Table Card"},
                          {url:"images/portfolio-lb/33_cw_trade_ad_1.png",
                           caption:"Trade Ad"},
                          {url:"images/portfolio-lb/34_cw_trade_ad_2.png",
                           caption:"Trade Ad"},
                          {url:"images/portfolio-lb/35_cw_trade_ad_3.png",
                           caption:"Trade Ad"},
                      ]
                  


                      $scope.openLightboxModal = function (index) {
                         Lightbox.openModal($scope.imagesLightbox, index);
                       };

                      $scope.openFirstIncludedLightboxModal = function (index) {
                         Lightbox.openModal($scope.imagesLightboxFirstIncluded, index);
                       };
      
    	


  });
