'use strict';

/**
 * @ngdoc function
 * @name tonygApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the tonygApp
 */
angular.module('tonygApp')
  .controller('MainCtrl', function ($scope, $animate, Lightbox) {

    $('#carousel-portfolio').carousel();

  	$scope.test = '../../images/logo.png';
  	$animate.enabled(true); 

    $scope.images = [
                      "images/portfolio/bcc_donate.png", 
                      "images/portfolio/bcc_logo.png", 
                      "images/portfolio/bcc_rack_brochure.png", 
                      "images/portfolio/bellflower_1.png", 
                      "images/portfolio/bellflower_2.png", 
                      "images/portfolio/bellflower_3.png", 
                      "images/portfolio/coh_centenial_book.png",
                      "images/portfolio/coh_dinner_invite.png",
                      "images/portfolio/coh_hem_brochure.png",
                      "images/portfolio/coh_hemmal_brochure-cover.png",
                      "images/portfolio/coh_hemmal_brochure-inside.png",
                      "images/portfolio/coh_kwak-postcard.png",
                      "images/portfolio/coh_physical-cover.png",
                      "images/portfolio/coh_physical-inside.png",
                      "images/portfolio/cw_bpd-email1.png",
                      "images/portfolio/cw_bpd-email2.png",
                      "images/portfolio/cw_bpd-letter.png",
                      "images/portfolio/cw_bpd-postcard.png",
                      "images/portfolio/cw_idtheft_1.png",
                      "images/portfolio/cw_idtheft_2.png",
                      "images/portfolio/cw_idtheft_3.png",
                      "images/portfolio/cw_idtheft_4.png",
                      "images/portfolio/cw_recruitment_1.png",
                      "images/portfolio/cw_recruitment_2.png",
                      "images/portfolio/cw_recruitment_3.png",
                      "images/portfolio/cw_trade_ad_1.png",
                      "images/portfolio/cw_trade_ad_2.png",
                      "images/portfolio/cw_trade_ad_3.png",
                      "images/portfolio/di_stargaze_ad.png",
                      "images/portfolio/di_stars_ad.png",
                      "images/portfolio/et_angels_ad_1.png",
                      "images/portfolio/et_angels_ad_2.png",
                      "images/portfolio/et_angels_ad_3.png",
                      "images/portfolio/et_angels_ad_4.png",
                      "images/portfolio/et_angels_insert_1.png",
                      "images/portfolio/et_angels_insert_2.png",
                      "images/portfolio/et_bullpen_banner.png",
                      "images/portfolio/et_fajita_banner.png",
                      "images/portfolio/et_menu-cover.png",
                      "images/portfolio/et_menu-inside.png",
                      "images/portfolio/et_shrimp_ad.png",
                      "images/portfolio/et_sunset_ad.png",
                      "images/portfolio/et_tablecard_1.png",
                      "images/portfolio/et_tablecard_2.png",
                      "images/portfolio/et_tablecard_3.png",
                      "images/portfolio/hamms_bank_ad.png",
                      "images/portfolio/mhl_pos_guide_1.png",
                      "images/portfolio/mhl_pos_guide_2.png",
                      "images/portfolio/mhl_pos_guide_3.png",
                      "images/portfolio/red_rocket_ad_1.png",
                      "images/portfolio/red_rocket_ad_2.png",
                      "images/portfolio/suzuki_outdoor.png",
                      "images/portfolio/tahiti_ad.png",
                      "images/portfolio/tf_degreesoflove.png",
                      "images/portfolio/tf_easter_email.1.png",
                      "images/portfolio/tf_easter_email.2.png",
                      "images/portfolio/tf_easter_email.3.png",
                      "images/portfolio/tf_howdoIlovethee.png",
                      "images/portfolio/tf_mday-postcard.png",
                      "images/portfolio/tf_snoopy.gif",
                      "images/portfolio/tf_takeherbreathaway.png",
                      "images/portfolio/tf_texasflorist-ad.png",
                      "images/portfolio/tf_thanks.gif",
                      "images/portfolio/tf_vday_email.1.png",
                      "images/portfolio/tf_xmas-poster.png",
                      "images/portfolio/wf_ad_1.png",
                      "images/portfolio/wf_ad_2.png",
                      "images/portfolio/wf_poster_1.png",
                      "images/portfolio/wf_poster_2.png",
                      "images/portfolio/wf_poster_3.png",
                      "images/portfolio/wf_poster_4.png",
                      "images/portfolio/wp_dm_letter.png",
                      "images/portfolio/bcc_banners.png",
                      ]

                      $scope.imagesLightbox = [
                      "images/portfolio-lb/bcc_donate.png", 
                      "images/portfolio-lb/bcc_logo.png", 
                      "images/portfolio-lb/bcc_rack_brochure.png", 
                      "images/portfolio-lb/bellflower_1.png", 
                      "images/portfolio-lb/bellflower_2.png", 
                      "images/portfolio-lb/bellflower_3.png", 
                      "images/portfolio-lb/coh_centenial_book.png",
                      "images/portfolio-lb/coh_dinner_invite.png",
                      "images/portfolio-lb/coh_hem_brochure.png",
                      "images/portfolio-lb/coh_hemmal_brochure-cover.png",
                      "images/portfolio-lb/coh_hemmal_brochure-inside.png",
                      "images/portfolio-lb/coh_kwak-postcard.png",
                      "images/portfolio-lb/coh_physical-cover.png",
                      "images/portfolio-lb/coh_physical-inside.png",
                      "images/portfolio-lb/cw_bpd-email1.png",
                      "images/portfolio-lb/cw_bpd-email2.png",
                      "images/portfolio-lb/cw_bpd-letter.png",
                      "images/portfolio-lb/cw_bpd-postcard.png",
                      "images/portfolio-lb/cw_idtheft_1.png",
                      "images/portfolio-lb/cw_idtheft_2.png",
                      "images/portfolio-lb/cw_idtheft_3.png",
                      "images/portfolio-lb/cw_idtheft_4.png",
                      "images/portfolio-lb/cw_recruitment_1.png",
                      "images/portfolio-lb/cw_recruitment_2.png",
                      "images/portfolio-lb/cw_recruitment_3.png",
                      "images/portfolio-lb/cw_trade_ad_1.png",
                      "images/portfolio-lb/cw_trade_ad_2.png",
                      "images/portfolio-lb/cw_trade_ad_3.png",
                      "images/portfolio-lb/di_stargaze_ad.png",
                      "images/portfolio-lb/di_stars_ad.png",
                      "images/portfolio-lb/et_angels_ad_1.png",
                      "images/portfolio-lb/et_angels_ad_2.png",
                      "images/portfolio-lb/et_angels_ad_3.png",
                      "images/portfolio-lb/et_angels_ad_4.png",
                      "images/portfolio-lb/et_angels_insert_1.png",
                      "images/portfolio-lb/et_angels_insert_2.png",
                      "images/portfolio-lb/et_bullpen_banner.png",
                      "images/portfolio-lb/et_fajita_banner.png",
                      "images/portfolio-lb/et_menu-cover.png",
                      "images/portfolio-lb/et_menu-inside.png",
                      "images/portfolio-lb/et_shrimp_ad.png",
                      "images/portfolio-lb/et_sunset_ad.png",
                      "images/portfolio-lb/et_tablecard_1.png",
                      "images/portfolio-lb/et_tablecard_2.png",
                      "images/portfolio-lb/et_tablecard_3.png",
                      "images/portfolio-lb/hamms_bank_ad.png",
                      "images/portfolio-lb/mhl_pos_guide_1.png",
                      "images/portfolio-lb/mhl_pos_guide_2.png",
                      "images/portfolio-lb/mhl_pos_guide_3.png",
                      "images/portfolio-lb/red_rocket_ad_1.png",
                      "images/portfolio-lb/red_rocket_ad_2.png",
                      "images/portfolio-lb/suzuki_outdoor.png",
                      "images/portfolio-lb/tahiti_ad.png",
                      "images/portfolio-lb/tf_degreesoflove.png",
                      "images/portfolio-lb/tf_easter_email.1.png",
                      "images/portfolio-lb/tf_easter_email.2.png",
                      "images/portfolio-lb/tf_easter_email.3.png",
                      "images/portfolio-lb/tf_howdoIlovethee.png",
                      "images/portfolio-lb/tf_mday-postcard.png",
                      "images/portfolio-lb/tf_snoopy.gif",
                      "images/portfolio-lb/tf_takeherbreathaway.png",
                      "images/portfolio-lb/tf_texasflorist-ad.png",
                      "images/portfolio-lb/tf_thanks.gif",
                      "images/portfolio-lb/tf_vday_email.1.png",
                      "images/portfolio-lb/tf_xmas-poster.png",
                      "images/portfolio-lb/wf_ad_1.png",
                      "images/portfolio-lb/wf_ad_2.png",
                      "images/portfolio-lb/wf_poster_1.png",
                      "images/portfolio-lb/wf_poster_2.png",
                      "images/portfolio-lb/wf_poster_3.png",
                      "images/portfolio-lb/wf_poster_4.png",
                      "images/portfolio-lb/wp_dm_letter.png",
                      "images/portfolio-lb/bcc_banners.png",
                      ]

                      $scope.imagesLightboxFirstIncluded = [ 
                      "images/portfolio-lb/bcc_banners.png",
                      "images/portfolio-lb/bcc_donate.png", 
                      "images/portfolio-lb/bcc_logo.png", 
                      "images/portfolio-lb/bcc_rack_brochure.png", 
                      "images/portfolio-lb/bellflower_1.png", 
                      "images/portfolio-lb/bellflower_2.png", 
                      "images/portfolio-lb/bellflower_3.png", 
                      "images/portfolio-lb/coh_centenial_book.png",
                      "images/portfolio-lb/coh_dinner_invite.png",
                      "images/portfolio-lb/coh_hem_brochure.png",
                      "images/portfolio-lb/coh_hemmal_brochure-cover.png",
                      "images/portfolio-lb/coh_hemmal_brochure-inside.png",
                      "images/portfolio-lb/coh_kwak-postcard.png",
                      "images/portfolio-lb/coh_physical-cover.png",
                      "images/portfolio-lb/coh_physical-inside.png",
                      "images/portfolio-lb/cw_bpd-email1.png",
                      "images/portfolio-lb/cw_bpd-email2.png",
                      "images/portfolio-lb/cw_bpd-letter.png",
                      "images/portfolio-lb/cw_bpd-postcard.png",
                      "images/portfolio-lb/cw_idtheft_1.png",
                      "images/portfolio-lb/cw_idtheft_2.png",
                      "images/portfolio-lb/cw_idtheft_3.png",
                      "images/portfolio-lb/cw_idtheft_4.png",
                      "images/portfolio-lb/cw_recruitment_1.png",
                      "images/portfolio-lb/cw_recruitment_2.png",
                      "images/portfolio-lb/cw_recruitment_3.png",
                      "images/portfolio-lb/cw_trade_ad_1.png",
                      "images/portfolio-lb/cw_trade_ad_2.png",
                      "images/portfolio-lb/cw_trade_ad_3.png",
                      "images/portfolio-lb/di_stargaze_ad.png",
                      "images/portfolio-lb/di_stars_ad.png",
                      "images/portfolio-lb/et_angels_ad_1.png",
                      "images/portfolio-lb/et_angels_ad_2.png",
                      "images/portfolio-lb/et_angels_ad_3.png",
                      "images/portfolio-lb/et_angels_ad_4.png",
                      "images/portfolio-lb/et_angels_insert_1.png",
                      "images/portfolio-lb/et_angels_insert_2.png",
                      "images/portfolio-lb/et_bullpen_banner.png",
                      "images/portfolio-lb/et_fajita_banner.png",
                      "images/portfolio-lb/et_menu-cover.png",
                      "images/portfolio-lb/et_menu-inside.png",
                      "images/portfolio-lb/et_shrimp_ad.png",
                      "images/portfolio-lb/et_sunset_ad.png",
                      "images/portfolio-lb/et_tablecard_1.png",
                      "images/portfolio-lb/et_tablecard_2.png",
                      "images/portfolio-lb/et_tablecard_3.png",
                      "images/portfolio-lb/hamms_bank_ad.png",
                      "images/portfolio-lb/mhl_pos_guide_1.png",
                      "images/portfolio-lb/mhl_pos_guide_2.png",
                      "images/portfolio-lb/mhl_pos_guide_3.png",
                      "images/portfolio-lb/red_rocket_ad_1.png",
                      "images/portfolio-lb/red_rocket_ad_2.png",
                      "images/portfolio-lb/suzuki_outdoor.png",
                      "images/portfolio-lb/tahiti_ad.png",
                      "images/portfolio-lb/tf_degreesoflove.png",
                      "images/portfolio-lb/tf_easter_email.1.png",
                      "images/portfolio-lb/tf_easter_email.2.png",
                      "images/portfolio-lb/tf_easter_email.3.png",
                      "images/portfolio-lb/tf_howdoIlovethee.png",
                      "images/portfolio-lb/tf_mday-postcard.png",
                      "images/portfolio-lb/tf_snoopy.gif",
                      "images/portfolio-lb/tf_takeherbreathaway.png",
                      "images/portfolio-lb/tf_texasflorist-ad.png",
                      "images/portfolio-lb/tf_thanks.gif",
                      "images/portfolio-lb/tf_vday_email.1.png",
                      "images/portfolio-lb/tf_xmas-poster.png",
                      "images/portfolio-lb/wf_ad_1.png",
                      "images/portfolio-lb/wf_ad_2.png",
                      "images/portfolio-lb/wf_poster_1.png",
                      "images/portfolio-lb/wf_poster_2.png",
                      "images/portfolio-lb/wf_poster_3.png",
                      "images/portfolio-lb/wf_poster_4.png",
                      "images/portfolio-lb/wp_dm_letter.png",
                      ]
                  


                      $scope.openLightboxModal = function (index) {
                         Lightbox.openModal($scope.imagesLightbox, index);
                       };

                      $scope.openFirstIncludedLightboxModal = function (index) {
                         Lightbox.openModal($scope.imagesLightboxFirstIncluded, index);
                       };
      
    	


  });
